//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Karamem0.BookingServiceBot.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class StringResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Karamem0.BookingServiceBot.Resources.StringResources", typeof(StringResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ビジネス.
        /// </summary>
        public static string BookingBusinessLabel {
            get {
                return ResourceManager.GetString("BookingBusinessLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 電子メール アドレス.
        /// </summary>
        public static string BookingCustomerEmailLabel {
            get {
                return ResourceManager.GetString("BookingCustomerEmailLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 名前.
        /// </summary>
        public static string BookingCustomerNameLabel {
            get {
                return ResourceManager.GetString("BookingCustomerNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 終了時刻.
        /// </summary>
        public static string BookingEndTimeLabel {
            get {
                return ResourceManager.GetString("BookingEndTimeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to サービス.
        /// </summary>
        public static string BookingServiceLabel {
            get {
                return ResourceManager.GetString("BookingServiceLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 開始時刻.
        /// </summary>
        public static string BookingStartTimeLabel {
            get {
                return ResourceManager.GetString("BookingStartTimeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 予約は実行されませんでした。.
        /// </summary>
        public static string CancelBookingMessage {
            get {
                return ResourceManager.GetString("CancelBookingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to キャンセル.
        /// </summary>
        public static string CancelText {
            get {
                return ResourceManager.GetString("CancelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 予約するビジネスを選択してください。.
        /// </summary>
        public static string ChooseBookingBusinessMessage {
            get {
                return ResourceManager.GetString("ChooseBookingBusinessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 予約する日付を選択してください。.
        /// </summary>
        public static string ChooseBookingDateMessage {
            get {
                return ResourceManager.GetString("ChooseBookingDateMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 予約するサービスを選択してください。.
        /// </summary>
        public static string ChooseBookingServiceMessage {
            get {
                return ResourceManager.GetString("ChooseBookingServiceMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 予約する時刻を選択してください。.
        /// </summary>
        public static string ChooseBookingTimeMessage {
            get {
                return ResourceManager.GetString("ChooseBookingTimeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 予約が完了しました。.
        /// </summary>
        public static string CompleteBookingMessage {
            get {
                return ResourceManager.GetString("CompleteBookingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 予約する内容はこれでよろしいですか？.
        /// </summary>
        public static string ConfirmBookingMessage {
            get {
                return ResourceManager.GetString("ConfirmBookingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 予約する人の電子メール アドレスを入力してください。.
        /// </summary>
        public static string EnterBookingCustomerEmailMessage {
            get {
                return ResourceManager.GetString("EnterBookingCustomerEmailMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 予約する人の名前を入力してください。.
        /// </summary>
        public static string EnterBookingCustomerNameMessage {
            get {
                return ResourceManager.GetString("EnterBookingCustomerNameMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to こんにちは。予約サービスにようこそ。[キャンセル] と入力するといつでもキャンセルできます。.
        /// </summary>
        public static string HelloMessage {
            get {
                return ResourceManager.GetString("HelloMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 指定した日付には空き時間がありません。日付を選択しなおしてください。.
        /// </summary>
        public static string RetryBookingDateMessage {
            get {
                return ResourceManager.GetString("RetryBookingDateMessage", resourceCulture);
            }
        }
    }
}
